import { ICommonFieldForm } from "../../Interfaces/commonFormsFields";
export const driverSchemaTypes: ICommonFieldForm = {
  title: "Driver ",
  fields: [
    {
      fieldName: "firstName",
      required: true,
      label: "First Name",
      type: "text",
      id: "firstName",
    },
    {
      fieldName: "lastName",
      required: true,
      label: "lastName",
      type: "text",
      id: "lastName",
    },
    {
      fieldName: "contactNumber",
      required: true,
      label: "Contact Number",
      type: "text",
      id: "contactNumber",
    },
    {
      fieldName: "email",
      required: true,
      label: "Email",
      type: "text",
      id: "email",
    },
    {
      fieldName: "dob",
      required: true,
      label: "DOB",
      type: "date",
      id: "dob",
    },
    {
      fieldName: "bloodGroup",
      required: true,
      label: "Blood Group",
      type: "select",
      defaultValue: 0,
      options: [
        {
          value: 0,
          menuItem: "Choose Blood Group",
          disabled: true,
        },
        { value: "A+", menuItem: "A+" },
        { value: "A-", menuItem: "A-" },
        { value: "B+", menuItem: "B+" },
        { value: "B-", menuItem: "B-" },
        { value: "AB+", menuItem: "AB+" },
        { value: "AB-", menuItem: "AB-" },
        { value: "O+", menuItem: "O+" },
        { value: "O-", menuItem: "O-" },
      ],
    },
    {
      fieldName: "licenseClass",
      required: true,
      label: "License Class",
      type: "select",
      defaultValue: 0,
      options: [
        {
          value: 0,
          menuItem: "Choose License Class",
          disabled: true,
        },
        { value: "LTV", menuItem: "LTV" },
        { value: "HTV", menuItem: "HTV" },
        { value: "Motorbike/rickshaw", menuItem: "Motorbike/rickshaw" },
        { value: "PSV", menuItem: "PSV" },
      ],

      id: " licenseClass",
    },
    {
      fieldName: "address",
      required: true,
      label: "Address",
      type: "text",
      id: "address",
    },
    {
      fieldName: "expiryDate",
      required: true,
      label: "Expiry Date",
      type: "date",
      id: " expiryDate",
    },
    {
      fieldName: "licenseNumber",
      required: true,
      label: "License Number",
      type: "text",
      id: "licenseNumber",
    },
    {
      fieldName: "experience",
      required: true,   
      label: "Experience in vehicles :",
      type: "checkbox",
      defaultValue: [],
      options: ["Truck", "Sedan", "SUV"],
    },
    {
      fieldName: "gender",
      label: "Gender",
      type: "radio",
      defaultValue: "",
      options: [
        {
          menuItem: "Male",
          value: "male",
        },
        {
          menuItem: "Female",
          value: "female",
        },
      ],
    },
    {
      fieldName: "additionalInformation",
      label: "Additional Information:",
      defaultValue: "",
      type: "textArea",
    },
    {
      fieldName: "isAgree",
      required: true,
      label: "I agree to the terms & conditions",
      defaultValue: false,
      type: "checkbox",
    },
  ],
};
